scores:
  alliance:
    - 5
    - 1
  normal:
    - 8
    - 7
    - 6
    - 5
    - 4
    - 3
    - 2
    - 1
teams:
    - name: A
      strength: 1
      alliance: A
    - name: B
      strength: 1
      alliance: A
    - name: C
      strength: 1
      alliance: A
    - name: D
      strength: 1
      alliance: A
    - name: E
      strength: 1
      alliance: B
    - name: F
      strength: 1
      alliance: B
    - name: G
      strength: 1
      alliance: B
    - name: H
      strength: 1
      alliance: B
events:
  alliance: 5
  normal: 10
